export const PRODUCT_LIST = [
  {
    categoryId: 1,
    slug: "category-1",
    name: "Category 1",
    product: [
      {
        id: 1,
        name: "Product A",
        slug: "product-a",
        desc: "Short Description",
        trending: true,
        price: 10000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
      {
        id: 2,
        name: "Product B",
        slug: "product-b",
        desc: "Short Description",
        trending: true,
        price: 20000,
        discount: 10,
        stock: 10,
        addition: [1, 2],
      },
      {
        id: 3,
        name: "Product C",
        slug: "product-c",
        desc: "Short Description",
        trending: false,
        price: 30000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
      {
        id: 4,
        name: "Product D",
        slug: "product-d",
        desc: "Short Description",
        trending: false,
        price: 40000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
      {
        id: 5,
        name: "Product E",
        slug: "product-e",
        desc: "Short Description",
        trending: false,
        price: 50000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
    ],
  },
  {
    categoryId: 2,
    slug: "category-2",
    name: "Category 2",
    product: [
      {
        id: 6,
        name: "Product F",
        slug: "product-f",
        desc: "Short Description",
        trending: true,
        price: 60000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
      {
        id: 7,
        name: "Product G",
        slug: "product-g",
        desc: "Short Description",
        trending: true,
        price: 70000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
      {
        id: 8,
        name: "Product H",
        slug: "product-h",
        desc: "Short Description",
        trending: false,
        price: 80000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
      {
        id: 9,
        name: "Product I",
        slug: "product-i",
        desc: "Short Description",
        trending: false,
        price: 90000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
      {
        id: 10,
        name: "Product J",
        slug: "product-j",
        desc: "Short Description",
        trending: false,
        price: 100000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
    ],
  },
  {
    categoryId: 3,
    slug: "category-3",
    name: "Category 3",
    product: [
      {
        id: 11,
        name: "Product K",
        slug: "product-k",
        desc: "Short Description",
        trending: true,
        price: 110000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
      {
        id: 12,
        name: "Product L",
        slug: "product-l",
        desc: "Short Description",
        trending: true,
        price: 120000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
      {
        id: 13,
        name: "Product M",
        slug: "product-m",
        desc: "Short Description",
        trending: false,
        price: 130000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
      {
        id: 14,
        name: "Product N",
        slug: "product-n",
        desc: "Short Description",
        trending: false,
        price: 140000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
      {
        id: 15,
        name: "Product O",
        slug: "product-o",
        desc: "Short Description",
        trending: false,
        price: 150000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
    ],
  },
  {
    categoryId: 4,
    slug: "category-4",
    name: "Category 4",
    product: [
      {
        id: 16,
        name: "Product P",
        slug: "product-p",
        desc: "Short Description",
        trending: false,
        price: 160000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
      {
        id: 17,
        name: "Product Q",
        slug: "product-q",
        desc: "Short Description",
        trending: false,
        price: 170000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
      {
        id: 18,
        name: "Product R",
        slug: "product-r",
        desc: "Short Description",
        trending: false,
        price: 180000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
      {
        id: 19,
        name: "Product S",
        slug: "product-s",
        desc: "Short Description",
        trending: false,
        price: 190000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
      {
        id: 20,
        name: "Product T",
        slug: "product-t",
        desc: "Short Description",
        trending: true,
        price: 200000,
        discount: 0,
        stock: 10,
        addition: [1, 2],
      },
    ],
  },
];
